### ISSUE TITLE
Does not work with language-javascript-jsx by subtlegradient

### ISSUE THREAD

**Issue by CodeAmend** [nkt/atom-autocomplete-modules#65]
I cannot get this to work with language-javascript-jsx by subtlegradient. 
If I disable language-javascript-jsx it works. 

atom -v 1.16.0
language-javascript-jsx -v 0.3.7
autocomplete-modules -v 1.6.9

**Comment by CodeAmend** [comment]
Yeah, Still doesn't work. This are both great packages. I cannot use them at same time.

**Comment by nkt** [comment]
Hello, thanks for reporting. I've tried to install this package and it works fine with autocomplete.
Try to disable other autocomplete providers.

**Comment by quanru** [comment]
+1

**Comment by jonyeezs** [comment]
@CodeAmend, @monojack, @quanru is this still a problem for you?

**Comment by jonyeezs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest stable version and then please use the [issue template](../blob/master/ISSUE_TEMPLATE.md). You can also contribute directly by providing a pull request :100: :heart:!

Thank you!
