### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined????

### ISSUE THREAD

**Issue by yunshangyue** [nkt/atom-autocomplete-modules#97]

**Comment by jonyeezs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest stable version and then please use the [issue template](../blob/master/ISSUE_TEMPLATE.md). You can also contribute directly by providing a pull request :100: :heart:!

Thank you!
